import { PrismaClient } from '@prisma/client';

export const seed = (prisma: PrismaClient) =>
	prisma.constellation.createMany({
		data: [
			'Andromeda',
			'Antlia',
			'Apus',
			'Aquarius',
			'Aquila',
			'Ara',
			'Aries',
			'Auriga',
			'Boötes',
			'Caelum',
			'Camelopardalis',
			'Cancer',
			'Canes Venatici',
			'Canis Major',
			'Canis Minor',
			'Capricornus',
			'Carina',
			'Cassiopeia',
			'Centaurus',
			'Cepheus',
			'Cetus',
			'Chamaeleon',
			'Circinus',
			'Columba',
			'Coma Berenices',
			'Corona Australis',
			'Corona Borealis',
			'Corvus',
			'Crater',
			'Crux',
			'Cygnus',
			'Delphinus',
			'Dorado',
			'Draco',
			'Equuleus',
			'Eridanus',
			'Fornax',
			'Gemini',
			'Grus',
			'Hercules',
			'Horologium',
			'Hydra',
			'Hydrus',
			'Indus',
			'Lacerta',
			'Leo Minor',
			'Leo',
			'Lepus',
			'Libra',
			'Lupus',
			'Lynx',
			'Lyra',
			'Mensa',
			'Microscopium',
			'Monoceros',
			'Musca',
			'Norma',
			'Octans',
			'Ophiuchus',
			'Orion',
			'Pavo',
			'Pegasus',
			'Perseus',
			'Phoenix',
			'Pictor',
			'Pisces',
			'Piscis Austrinus',
			'Puppis',
			'Pyxis',
			'Reticulum',
			'Sagitta',
			'Sagittarius',
			'Scorpius',
			'Sculptor',
			'Scutum',
			'Serpens',
			'Sextans',
			'Taurus',
			'Telescopium',
			'Triangulum Australe',
			'Triangulum',
			'Tucana',
			'Ursa Major',
			'Ursa Minor',
			'Vela',
			'Virgo',
			'Volans',
			'Vulpecula'
		].map(c => ({ name: c })),
	});
